import pandas as pd
import numpy as np
from re import split



pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 200)
pd.set_option('display.width', 1000)


def camelize(string):
 s = ''.join([a.capitalize() for a in split('([^a-zA-Z0-9])', string) if a.isalnum()])
 return s[0].lower() + s[1:]


frame = pd.read_csv('./player_data/phs-2022.csv')
stats = frame['stat_name'].unique()
for s in stats:
 print(f"'{s}',")
#
stats_to_care = [
'All Damage Done',
'Assists',
'Barrier Damage Done',
'Damage - Quick Melee',
'Damage Done',
'Damage Taken',
'Deaths',
'Defensive Assists',
'Eliminations',
'Environmental Kills',
'Final Blows',
'Healing Done',
'Hero Damage Done',
'Knockback Kills',
'Objective Kills',
'Objective Time',
'Offensive Assists',
'Shots Fired',
'Time Alive',
'Time Building Ultimate',
'Time Holding Ultimate',
'Time Played',
'Ultimates Earned - Fractional',
'Ultimates Used',
'Amped Heal Activations',
'Amped Speed Activations',
'Critical Hit Kills',
'Critical Hits',
'Damage - Weapon Primary',
'Damage - Weapon Secondary',
'Games Played',
'Games Won',
'Heal Song Time Elapsed',
'Healing - Healing Boost',
'Healing - Healing Boost Amped',
'Healing Received',
'Players Knocked Back',
'Quick Melee Hits',
'Quick Melee Ticks',
'Self Healing',
'Shots Hit',
'Shots Missed',
'Sound Barrier Casts',
'Sound Barriers Provided',
'Soundwave Kills',
'Speed Song Time Elapsed',
'Melee Final Blows',
'Damage - Deflect',
'Damage - Dragonblade',
'Damage - Dragonblade Total',
'Damage - Swift Strike',
'Damage - Swift Strike Dragonblade',
'Damage Reflected',
'Deflection Kills',
'Dragonblade Kills',
'Dragonblades',
'Damage - Weapon',
'Health Recovered',
'Match Blinks Used',
'Recalls Used',
'Damage Blocked',
'Solo Kills',
'Ability Damage Done',
'Damage - Rocket Punch',
'Damage - Seismic Slam',
'Shields Created',
'Damage - Jump Pack',
'Damage - Primal Rage Leap',
'Damage - Primal Rage Melee',
'Damage - Primal Rage Total',
'Jump Pack Kills',
'Melee Kills',
'Primal Rage Kills',
'Primal Rage Melee Hits',
'Primal Rage Melee Hits - Multiple',
'Primal Rage Melee Ticks',
'Tesla Cannon Hits',
'Tesla Cannon Hits - Multiple',
'Tesla Cannon Ticks',
'Weapon Kills',
'Damage - Death Blossom',
'Death Blossom Kills',
'Death Blossoms',
'Biotic Field Healing Done',
'Biotic Fields Deployed',
'Damage - Helix Rockets',
'Damage - Tactical Visor',
'Helix Rocket Kills',
'Tactical Visor Kills',
'Tactical Visors',
'Biotic Grenade Kills',
'Damage - Biotic Grenade',
'Damage - Weapon Scoped',
'Enemies Slept',
'Healing - Biotic Grenade',
'Healing - Weapon',
'Healing - Weapon Scoped',
'Healing Amplified',
'Nano Boost Assists',
'Nano Boosts Applied',
'Scoped Hits',
'Scoped Shots',
'Sleep Dart Hits',
'Sleep Dart Shots',
'Unscoped Hits',
'Unscoped Shots',
'Environmental Deaths',
'Damage - Graviton Surge',
'Energy Maximum',
'Graviton Surge Kills',
'High Energy Kills',
'Lifetime Energy Accumulation',
'Primary Fire Hits',
'Primary Fire Ticks',
'Projected Barriers Applied',
'Damage - Duplicate',
'Damage - Focusing Beam',
'Damage - Focusing Beam - Bonus Damage Only',
'Damage - Sticky Bombs',
'Duplicate Kills',
'Focusing Beam Dealing Damage Seconds',
'Focusing Beam Kills',
'Focusing Beam Seconds',
'Sticky Bombs Direct Hits',
'Sticky Bombs Kills',
'Sticky Bombs Used',
'Damage - Pulse Bomb',
'Scoped Critical Hit Kills',
'Scoped Critical Hits',
'Bob Gun Damage',
'Bob Kills',
'Coach Gun Kills',
'Damage - Bob',
'Damage - Coach Gun',
'Damage - Dynamite',
'Dynamite Kills',
'Damage - Boosters',
'Damage - Micro Missiles',
'Damage - Pistol',
'Damage - Self Destruct',
'Mech Deaths',
'Mechs Called',
'Self-Destructs',
'Recon Assists',
'Damage - Venom Mine',
'Infra-sight Uptime',
'Venom Mine Kills',
'Multikills',
'Accretion Kills',
'Accretion Stuns',
'Damage - Accretion',
'Damage - Hyperspheres',
'Damage Absorbed',
'Gravitic Flux Damage Done',
'Gravitic Flux Kills',
'Hyperspheres Direct Hits',
'Pulse Bomb Kills',
'Pulse Bombs Attached',
'Amplification Matrix Assists',
'Amplification Matrix Casts',
'Biotic Launcher Healing Explosions',
'Biotic Launcher Healing Shots',
'Damage Amplified',
'Damage Prevented',
'Healing - Biotic Launcher',
'Healing - Regenerative Burst',
'Immortality Field Deaths Prevented',
'Damage - Discord Orb',
'Damage - Weapon Charged',
'Discord Orb Time',
'Harmony Orb Time',
'Healing - Harmony Orb',
'Healing - Transcendence',
'Transcendence Healing',
'Time Discorded',
'Players Teleported',
'Teleporter Uptime',
'Teleporters Placed',
'Biotic Orb Maximum Damage',
'Biotic Orb Maximum Healing',
'Coalescence Healing',
'Damage - Biotic Orb',
'Damage - Coalescence',
'Healing - Biotic Orb',
'Healing - Coalescence',
'Healing - Secondary Fire',
'Secondary Fire Hits',
'Secondary Fire Ticks',
'Enemies EMP\'d',
'Enemies Hacked',
'Time Hacked',
'Armor - Rally',
'Armor Provided',
'Damage - Shield Bash',
'Healing - Inspire',
'Healing - Repair Pack',
'Inspire Uptime',
'Damage - Meteor Strike',
'Meteor Strike Kills',
'Blizzard Kills',
'Damage - Blizzard',
'Enemies Frozen',
'Freeze Spray Damage',
'Icicle Damage',
'Successful Freezes',
'Total Time Frozen',
'Healing - Immortality Field',
'Charge Kills',
'Damage - Charge',
'Damage - Earthshatter',
'Damage - Fire Strike',
'Earthshatter Kills',
'Earthshatter Stuns',
'Fire Strike Kills',
'Rocket Hammer Melee Hits',
'Rocket Hammer Melee Hits - Multiple',
'Rocket Hammer Melee Ticks',
'Damage - Chain Hook',
'Enemies Hooked',
'Hooks Attempted',
'Healing - Weapon Valkyrie',
'Players Resurrected',
'Players Saved',
'Damage - Call Mech',
'Coalescence Kills',
'Damage - Bob Charge',
'Barrage Kills',
'Damage - Barrage',
'Rocket Barrages',
'Rocket Direct Hits',
'of Rockets Fired',
'Self-Destruct Kills',
'Teleporter Pads Destroyed',
'Damage - Dragonstrike',
'Damage - Sonic',
'Damage - Storm Arrows',
'Dragonstrike Kills',
'Storm Arrow Kills',
'Railgun Shots',
'Damage - Sentry Turret',
'Photon Projector Kills',
'Primary Fire Hits Hits - Level',
'Secondary Direct Hits',
'Sentry Turret Kills',
'Turrets Destroyed',
'Concussion Mine Kills',
'Damage - Concussion Mine',
'Damage - RIP-Tire',
'Damage - Steel Trap',
'Damage - Total Mayhem',
'Enemies Trapped',
'Frag Launcher Direct Hits',
'Assault Damage',
'Damage - Weapon Sentry',
'Sentry Kills',
'Ultimates Negated',
'Blaster Kills',
'Damage - Weapon Pistol',
'Damage - Weapon Recon',
'Grenade Damage',
'Grappling Claw Uses',
'Roll Uptime',
'Roll Uses',
'Damage - Deadeye',
'Deadeye Kills',
'Damage - Molten Core',
'Overload Kills',
'Torbjörn Kills',
'Turret Damage',
'Turret Kills',
'Damage - Railgun',
'Railgun Hits',
'Fan the Hammer Kills',
'Adaptive Shield Uses',
'Air Uptime',
'Damage - Grappling Claw',
'Damage Taken - Adaptive Shield',
'Damage Taken - Ball',
'Grappling Claw Impacts',
'Shielding - Adaptive Shield',
'Recon Kills',
'Molten Core Kills',
'Damage - Piledriver',
'Damage Taken - Tank',
'Grappling Claw Kills',
'Piledriver Kills',
'Piledriver Uses',
'Javelin Damage',
'Overclock Kills',
'Railgun Critical Hit Kills',
'Railgun Critical Hits',
'Railgun Kills',
'Damage - Minefield',
'Minefield Kills',
'RIP-Tire Kills',
'Damage - Whole Hog',
'Whole Hog Kills',
'Carnage Kills',
'Jagged Blade Attempts',
'Jagged Blade Hits',
'Jagged Blade Kills',
'Rampage Kills',
'Wound Uptime',
'Terra Surge Kills',
]


#
# for s in stats_to_care:
#  print("""
#  <ng-container matColumnDef="%s">
#   <th mat-header-cell *matHeaderCellDef> %s </th>
#   <td mat-cell *matCellDef="let row"> {{row.%s}}} </td>
#  </ng-container>
#  """ % (camelize(s), s, camelize(s)))
#
# frame = frame[frame['Stat'].isin(stats_to_care)].drop_duplicates()
# opponents = frame[['Match Id', 'Map Name', 'Team Name', 'Classification']].drop_duplicates()
# opponents.columns = ['Match Id', 'Map Name', 'Opponent Team Name', 'Opponent Classification']
# frame = frame.merge(opponents, on=['Match Id', 'Map Name'])
# frame = frame[frame['Team Name'] != frame['Opponent Team Name']]
#
# frame.to_csv('./out/hero_data_2022.csv', index=False)
# frame[['Stat']].drop_duplicates().to_csv('./out/stats.csv', index=False)


